Update systex25.xml
Fix: invalid sha1 reference in manifest for build.
```
error: Downloading network changes failed.
Failing repos (network):
opencca-build
Try re-running with "-j1 --fail-fast" to exit at the first error.
================================================================================
Repo command failed due to the following `SyncError` errors:
GitCommandError: 'update-ref -m manifest set to 89d62d36b268fb7f7d84b3b1e98b9c6fa9d0bb60 --no-deref refs/remotes/m/opencca/systex25 89d62d36b268fb7f7d84b3b1e98b9c6fa9d0bb60^0' on opencca/opencca-build failed
stderr: fatal: 89d62d36b268fb7f7d84b3b1e98b9c6fa9d0bb60^0: not a valid SHA1
```